Header feature branch
DammyShittu/Portfolio-Project pull request #1
Opened 2021-07-07 18:16 UTC by DammyShittu

Created;
1) Mobile View Header and
2) Mobile View Headline

2021-07-07 19:53 UTC, hemant-soni-vst-au4 requested changes
Hi @DammyShittu, 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there! 

![Alt Text](https://media.giphy.com/media/q6U4fbreC4Neo/giphy.gif)
## Required Changes ♻️
_Check the comments under the review._

- [ ] Use of `<a>` tag for logo
- [ ] Change for background image
- [ ]  Add subheading in other heading tag
- [ ] Use `<ul>` tag for icons
- [ ] Make links active in `README` file



Cheers,
Hemant Soni
Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-07 19:53 UTC, hemant-soni-vst-au4 commented on README.md
> +LinkedIn: (linkedin.com/in/adedamola-shittu-3ab465172/)
- [ ] Kindly make the links active. Please follow this [link](https://github.com/microverseinc/readme-template) for `README` template.

2021-07-07 19:53 UTC, hemant-soni-vst-au4 commented on README.md
> +(https://dammyshittu.github.io/Portfolio-Project/)
- [ ] Please try to follow template guidelines to make the `live link`.  we can use `[Live Demo Link](https://dammyshittu.github.io/Portfolio-Project/)` to make the readme file more presentable.

2021-07-07 19:53 UTC, hemant-soni-vst-au4 commented on index.html
> +  </div>
- [ ] Please try to add logo in `<a>` tag. It will help the user to come back to the home page.

2021-07-07 19:53 UTC, hemant-soni-vst-au4 commented on index.html
> +   </div>
- [ ] Please try to add a proper background image as followed in the `Figma` design. The decorations are always background image, not `img` tags.

2021-07-07 19:53 UTC, hemant-soni-vst-au4 commented on index.html
> +    <p>Software Developer</p>
- [ ] Kindly try to add the `hx` tag for subtitle in place of the `<p>` tag. As per Html conventions, we have to use any other heading tag for subtitle.

2021-07-07 19:53 UTC, hemant-soni-vst-au4 commented on index.html
> +     </div>
- [ ] Please try to add `<ul>` and  `<li>` tag to group the list. And use the `<a>` tag for each icon.

2021-07-08 09:37 UTC, carlos-ssh approved these changes
Hi @DammyShittu , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-08 10:12 UTC, merged