Mobile menu with Javascript
DammyShittu/Portfolio-Project pull request #10
Opened 2021-07-26 16:49 UTC by DammyShittu

## In this pull request,

Functionality was added to the portfolio through Javascript.

The mobile menu of the portfolio was worked on. Hence, when the portfolio is being checked on screens with their width being less than or equal to 800px, the navbar is hidden and a hamburger is displayed.

*Javascript was added to fulfill the following requirements*

- When the user clicks (or taps) the hamburger button, the mobile menu appears.
- When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

2021-07-26 17:01 UTC, Shaher-11 requested changes
#### Hello @DammyShittu,

### Great job so far!
You have been doing an incredible  job on the project so far:clap::clap:
The project is very well structured:smiley::smiley:
However, we still need to make a few changes to get the project approved:muscle:

 ## Required Changes ♻️

- [ ] Check the comment  below:point_down:

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Happy Coding!👏👏👏

2021-07-26 17:37 UTC, Davidosky007 commented
# Hi @lily-coder @DammyShittu, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-26 17:41 UTC, merged

2021-07-27 07:26 UTC, rpire reviewed
Hello @DammyShittu and @lily-coder 

I like your work and everything you have done here, congratulations! 🤓

Cheers and Happy coding 🚀🙌

2021-07-27 07:28 UTC, rpire commented on style.css
> +
Nice trick there, I like it! 👍